### ISSUE TITLE
2 sampling dates - can we center plots on the page?

### ISSUE THREAD

**Issue by sbmarsh-USGS** [USGS-R/lakeReport#12]
These two sites only have 2 sampling dates.  Can we center the plots?

- [ ] 424840088241600 (Beulah Lake Deep)

- [ ] 424929088231300 (Beulah Lake Station 2)

![image](https://cloud.githubusercontent.com/assets/10731242/14683309/b056eca6-06ef-11e6-9239-e34dbe2d0437.png)

**Comment by lindsaycarr** [comment]
@sbmarsh-USGS merged in a fix for this with #36. Please test and close if it's working!

**Comment by sbmarsh-USGS** [comment]
Whohoo!
