### ISSUE TITLE
7 sampling dates - can we center the depth profile plots on the second page?

### ISSUE THREAD

**Issue by sbmarsh-USGS** [USGS-R/lakeReport#13]
With 7 sampling dates, the depth profile plot is generated with 4 dates on the first page and 3 dates on the second page.  Can we center the plots on the second page?
These sites have 7 sampling dates:

- [ ] 423556088365001 (Delavan Center)

- [ ] 423659088354401 (Delavan North)

- [ ] 423526088380101 (Delavan SW)

- [ ] 434928088570000 (Green East)

**Comment by lindsaycarr** [comment]
@sbmarsh-USGS merged in a fix for this with #36 and #37. Please test and close if it's working!

**Comment by sbmarsh-USGS** [comment]
This looks great now as far as the center goes.  I did notice that it makes the plots 2 different sizes though.  Plots on page 1 are bigger than on page 2.
![image](https://cloud.githubusercontent.com/assets/10731242/17902740/1d8bda16-692e-11e6-9e9c-563fc2735836.png)

![image](https://cloud.githubusercontent.com/assets/10731242/17902748/2601b2ec-692e-11e6-911f-7c3e03d36fa6.png)

**Comment by sbmarsh-USGS** [comment]
It actually didn't happen on all of them. But it did happen on the following stations:
Delavan SW (423526088380101), Delavan North (423659088354401), Delavan Center (423556088365001), Big Cedar South (432224088154900) - for this site, there a re 5 plots on one page, but they are the smaller size...smaller than 2 inches. Big Cedar North (432409088151600) - same as Big Cedar South, they are smaller.  I am only as far as Green Lake (alphabetically), so I haven't run them all yet.

**Comment by lindsaycarr** [comment]
That is because of the way we centered. Some of 4 plot slots (even if only two are filled), and some have 5 (even if only 3 or 1 are filled). I tried to play around a little bit here, but it's just a lot of trial and error. Think you could try it if I showed you what to change?

**Comment by sbmarsh-USGS** [comment]
Sure!

**Comment by sbmarsh-USGS** [comment]
This can be adjusted after copying and pasting.  Maybe we can tweak it more next year.
