### ISSUE TITLE
ghtable some sites are failing because no data is returned

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/lakeReport#20]
If you look at NWIS for the sites that fail, they do not have any gage height information available 

**Doesn't work: site number = 424840088241600**
http://waterdata.usgs.gov/nwis/inventory?agency_code=USGS&site_no=424840088241600
```r
wy <- 2014
siteNumber <- '424840088241600'
plotNames <- 'ghtable'
makeReports(siteNumber, wy, plotNames, 'word')
```

**Works: site number = 05390500**
http://waterdata.usgs.gov/nwis/inventory?agency_code=USGS&site_no=05390500
```r
wy <- 2014
siteNumber <- '05390500'
plotNames <- 'ghtable'
makeReports(siteNumber, wy, plotNames, 'word')
```

**Comment by lindsaycarr** [comment]
@sbmarsh-USGS should there be gage height data on NWIS for these sites? I remember this working before...

**Comment by sbmarsh-USGS** [comment]
No, not all sites have gage height data.  There is a stage_only_lakes file in SBMData>R>lakeReport>data   The one you listed above is not on the list of stage only lakes.

**Comment by lindsaycarr** [comment]
If you go to the link, NWIS does not look like it has stage data for that site. Unless I am trying to get it from the wrong place

**Comment by lindsaycarr** [comment]
The first site I tried should not be run for ghtable...it is wq only. Oops!
