### ISSUE TITLE
ghtable only populating dates where data exist

### ISSUE THREAD

**Issue by sbmarsh-USGS** [USGS-R/lakeReport#21]
Some gage height stations have only observer data..i.e., only on a few dates per year.  Can we make the tables so that they display all dates in the water year, but with dashes for days where there are no data.

**How R creates it:**
![image](https://cloud.githubusercontent.com/assets/10731242/15582463/cb305eaa-2336-11e6-80da-4092085a98a7.png)

**How it should look:**
![image](https://cloud.githubusercontent.com/assets/10731242/15582500/f6cf62d6-2336-11e6-9329-7b7954ac9eed.png)

**Comment by lindsaycarr** [comment]
closed thanks to #22
