### ISSUE TITLE
Collection of errors

### ISSUE THREAD

**Issue by sbmarsh-USGS** [USGS-R/lakeReport#23]

**Comment by sbmarsh-USGS** [comment]
example of a code block:

```r
wy <- 2015
siteNumber <- '445322088281801'
plotNames <- 'stagehydrograph'
makeReports(siteNumber, wy, plotNames, 'pdf')
```

**Comment by sbmarsh-USGS** [comment]
code block:
wy <- 2015
siteNumber <- '432409088151600'
plotNames <- 'depthprofiles'
output <- 'word'
makeReports(siteNumber, wy, plotNames, output)

0 reports successful

FAILED REPORTS:
       siteNumber      plotName
1 432409088151600 depthprofiles
Warning message:
running command '"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS depthprofiles.utf8.md --to docx --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output "D:/SBMData/R/lakeReport/2015/depthprofiles_2015_432409088151600.word" --highlight-style tango' had status 1

**Comment by sbmarsh-USGS** [comment]
```r 
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Peer certificate cannot be authenticated with given CA certificates
```

**Comment by sbmarsh-USGS** [comment]
Quitting from lines 18-32 (ghtable.Rmd) 



 0 reports successful

FAILED REPORTS:
  siteNumber plotName
1   05404500  ghtable

**Comment by lindsaycarr** [comment]
I'm going to close this. You've now gotten the hang of issues and can just create them as bugs come up :)
