### ISSUE TITLE
Station IDs in plotNames_by_site.csv file missing leading zeros or in scientific format

### ISSUE THREAD

**Issue by sbmarsh-USGS** [USGS-R/lakeReport#25]
Ok, I will focus on updating the plotNames_by_site.csv file.  I am noticing, though that the site_no column doesn't maintain the leading zero and also converts the 15-digit site numbers to scientific format.  I'm assuming this isn't an issue, though, since we've already generated lots of plots and tables. (yes?)

**Comment by lindsaycarr** [comment]
Where are you noticing this? Plots, tables, both? In the `plotNames_by_site.csv` file?

**Comment by sbmarsh-USGS** [comment]
The station IDs don't appear on the plots and tables and everything seems to be plotting and tabling okay (which seems odd).  When I went to add a new station to plotNames_by_site.csv, that's when I noticed it.

**Comment by lindsaycarr** [comment]
Can you put a screen shot up of the issue?

**Comment by sbmarsh-USGS** [comment]
See column B.

![image](https://cloud.githubusercontent.com/assets/10731242/16202606/fe0e7baa-36db-11e6-82d3-7b1b4ef3075f.png)

**Comment by lindsaycarr** [comment]
Are you only seeing this in the excel doc? If so, then this is not an issue because we have R specifically treating those numbers as string when it reads the csv

**Comment by sbmarsh-USGS** [comment]
Yep, only in Excel.  Great!  I wondered how everything was tabling/plotting okay....Thanks.
