### ISSUE TITLE
Time series plots scaling

### ISSUE THREAD

**Issue by sbmarsh-USGS** [USGS-R/lakeReport#26]
Could we add the following buffers/limits on the various scales for the time series plots?

- [x] Date scale (x-axis):  include all 12 months of start and end years (maybe this is correct already, but the labels and tick marks are goofy?)
- [x] TP scale (y-axis): use +0.05 of max. value for max line and -0.05 of min. value for min. line (or zero); don't go negative
- [x] Chlorophyll scale: use +1 of max value for max line and -1 of min. value for min. line (or zero); don't go negative
- [x] Secchi scale: use -0.5 of min. for top line (or zero) and +0.5 of max value for bottom line
- [x] TSI plot scale: Round to nearest tens value...i.e., if minimum value is 9, round down to 0.  If max value is 92, round up to 100.  Is this possible?

**Comment by lindsaycarr** [comment]
@sbmarsh-USGS yes - this all looks possible!

**Comment by lindsaycarr** [comment]
Date scale before/after

![image](https://cloud.githubusercontent.com/assets/13220910/16161695/8c95c88c-3494-11e6-8912-92adf12149cf.png)


![image](https://cloud.githubusercontent.com/assets/13220910/16161713/9cc4c0e6-3494-11e6-8e28-3e63280550fd.png)

**Comment by lindsaycarr** [comment]
![image](https://cloud.githubusercontent.com/assets/13220910/16162891/d29f4946-349b-11e6-93ac-e3881f3b461b.png)

**Comment by lindsaycarr** [comment]
@sbmarsh-USGS try grabbing my latest changes and see if this issue is good now. When you like the changes just click the "Close" button

Remember:
In RStudio >> Git tab of the Environment window >> More >> Shell
Then type:
```
git fetch upstream
git merge upstream/master
```
But you cannot have any un-committed work sitting in the Git tab or it will cause conflicts

**Comment by sbmarsh-USGS** [comment]
I just re-ran the qwtimeseries plots and here was the result:

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><p>No sites/data found using the selection criteria specified 
</p></body></html>

Quitting from lines 12-24 (qwtimeseries.Rmd) 



 0 reports successful

FAILED REPORTS:
   siteNumber     plotName
1     5390500 qwtimeseries
2    4.45E+14 qwtimeseries
3    4.25E+14 qwtimeseries
4    4.25E+14 qwtimeseries
5     5544099 qwtimeseries
6    4.32E+14 qwtimeseries
7    4.32E+14 qwtimeseries
8    4.52E+14 qwtimeseries
9    4.24E+14 qwtimeseries
10   4.24E+14 qwtimeseries
11   4.24E+14 qwtimeseries
12    5404500 qwtimeseries
13   4.24E+14 qwtimeseries
14   4.23E+14 qwtimeseries
15   4.35E+14 qwtimeseries
16   4.35E+14 qwtimeseries
17   4.35E+14 qwtimeseries
18    5401063 qwtimeseries
19   4.26E+14 qwtimeseries
20    5427235 qwtimeseries
21   4.41E+14 qwtimeseries
22    5428000 qwtimeseries
23   4.30E+14 qwtimeseries
24    5429000 qwtimeseries
25    5545000 qwtimeseries
26   4.31E+14 qwtimeseries
27   4.31E+14 qwtimeseries
28   4.31E+14 qwtimeseries
29   4.31E+14 qwtimeseries
30   4.31E+14 qwtimeseries
31   4.31E+14 qwtimeseries
32   4.31E+14 qwtimeseries
33   4.23E+14 qwtimeseries
34   4.53E+14 qwtimeseries
35    4072500 qwtimeseries
36    5429485 qwtimeseries
37   4.61E+14 qwtimeseries
38   4.25E+14 qwtimeseries
39   4.25E+14 qwtimeseries
40    4082500 qwtimeseries
41    4084255 qwtimeseries`

**Comment by sbmarsh-USGS** [comment]
new site: 
```
BOOT LAKE AT CAMP ROAD LANDING NEAR TOWNSEND, WI	
451559088383901 
TRUE	
TRUE	
FALSE	
FALSE	
FALSE
```

**Comment by sbmarsh-USGS** [comment]
Tick marks still look a little goofy.  There will be sites that don't need minor tick marks and sites that do, just based on how many years of data there are.  Maybe we should specify limits?...i.e., if less than 10 years of data, add minor ticks (to show 12 months); if between 10 and 20 years, show major tick for every year; if greater than 20 years of data, show major ticks for periodic intervals....just an example of limits.

![image](https://cloud.githubusercontent.com/assets/10731242/16244161/5a42a4b6-37c0-11e6-9e08-6b5584fd2ae6.png)

**Comment by lindsaycarr** [comment]
Did a little research on editing CSV's in Excel (and some trials on my own). I think the best way to add new sites to the csv would be to open it in a text editor (Notepad or Notepad++). It's not quite as pretty, but then you can ensure it is not switching numbers to scientific notation or dropping leading zeros. I'll commit the new site (Boot Lake) and then you can pull from upstream (and delete that new csv we made).

**Comment by ldecicco-USGS** [comment]
You can also use `dataRetrieval`'s `zeroPad` to specify leading zeros...shameless plug. Excel + USGS site numbers was the reason it was written.

**Comment by lindsaycarr** [comment]
That would be quite useful for the leading zero issue, but we're also having an issue where it returns longer site numbers in scientific notation and remains that way when you use `as.character` or read that column in as character

**Comment by lindsaycarr** [comment]
@sbmarsh-USGS for tick marks: are the y-axis marks good now? It's just the x-axis that could use some more logic?

**Comment by lindsaycarr** [comment]
@sbmarsh-USGS I followed your example logic exactly, see #32. You should be able to easily change the criteria if it does not work.

**Comment by lindsaycarr** [comment]
@sbmarsh-USGS please check if this works

**Comment by sbmarsh-USGS** [comment]
Looks good.
