### ISSUE TITLE
Times series plots Total Phosporus data limits

### ISSUE THREAD

**Issue by sbmarsh-USGS** [USGS-R/lakeReport#27]
For the TP plot on the time series plots, we only plot the minimum depth value....usually 0.5 m or 2 m or something like that.

**Comment by lindsaycarr** [comment]
@sbmarsh-USGS just want to make sure I understand this correctly - there will only be one total phosphorus value per day, and it was the value taken at the minimum depth?

**Comment by sbmarsh-USGS** [comment]
Yes, that's correct.

**Comment by lindsaycarr** [comment]
I can't seem to find where NWIS stores sample depth information for lake sites. Maybe @ldecicco-USGS knows?

**Comment by lindsaycarr** [comment]
Is there one value regardless of Observer or USGS?

**Comment by sbmarsh-USGS** [comment]
For TP, there should only be one value.  We typically don't have observers collecting this data for a lake site.

**Comment by lindsaycarr** [comment]
@sbmarsh-USGS  please close this issue if the latest code fixes it

Fix for this: https://github.com/USGS-R/lakeReport/blob/master/R/functions-qwtimeseries.R#L21-L26

```r
if(isTotalP){
  parm_data <- parm_data %>% 
    group_by(sample_dt) %>% 
    filter(sample_depth == min(sample_depth)) %>% 
    ungroup()
}
```

**Comment by sbmarsh-USGS** [comment]
Hmmm...in entering some missing observer data, I did notice that they occasionally sample on the same day we are there, so there might be secchi values on the same day.  Would this change how you code things?

**Comment by lindsaycarr** [comment]
It's currently taking the value for the sample taken at the minimum value for each day and ignores if that was USGS or observer. Is that the behavior you would like?

**Comment by sbmarsh-USGS** [comment]
I don't think so. I know I said 'yes' to that before, but the more I think about it, I don't want to miss the (very rare) occasion that there are observer data on the same day as USGS data...the main issue now becomes how it is distinguished it in our database.  Could we distinguish by "Result field comment"?  I may be able to figure out a way to batch load a comment into that field for the observer samples...

**Comment by sbmarsh-USGS** [comment]
Not sure which field/parameter list you pull from for the code....if it's from sample header information then the field in question is "Sample field comment".  See me if you have questions and I can show you in QWDATA.

**Comment by sbmarsh-USGS** [comment]
I also just noticed that the Total Phosphorus scale still seems a bit off for the plots...
![image](https://cloud.githubusercontent.com/assets/10731242/17216448/588a2312-54a6-11e6-88bd-57609ae120d6.png)
Chlorophyll and secchi are good, but the TP plot scale should have an upper limit somewhere around 0.07.

**Comment by lindsaycarr** [comment]
@sbmarsh-USGS in the `makeTimeseriesPlot` function, remove special Green Lake & secchi data filtering from see L64 - L70, and try removing isGreenLake & isSecchi from function definition and function calls.
