### ISSUE TITLE
limit data in ghtables to 2 decimal places

### ISSUE THREAD

**Issue by sbmarsh-USGS** [USGS-R/lakeReport#35]
Can we limit all ghtable values to 2 decimal places?  If so, can we round the data appropriately instead of just truncating it?

**Comment by lindsaycarr** [comment]
See #39 for changes. @sbmarsh-USGS this should be updated now

**Comment by sbmarsh-USGS** [comment]
Actually, several of the ghtables aren't even plotting now.  Which part of the error code do you need?

**Comment by lindsaycarr** [comment]
Just saw your errors - what you posted is perfect because I really need to see the number and report type. Unfortunately, we can't see what the exact errors are. 

I just tried running those myself and they appear to render just fine as word or PDF. Here is what I plugged in: 
```r
wy <- 2015
siteNumber <- '05404500'
plotNames <- 'ghtable'
makeReports(siteNumber, wy, plotNames, 'word')
```

**Comment by sbmarsh-USGS** [comment]
I just did that again, too, but mine fails.  ??

**Comment by lindsaycarr** [comment]
hmmmm. Go to the ghtable.Rmd file in your report templates folder. In that first code chunk, add these lines below `source("../R/functions-ghtable.R")`:

```r
source("../R/workflow-functions.R")
wy <- 2015
siteNumber <- '05404500'
output <- 'word'
``

Then save and click "Knit Word" on the tool bar. You should be able to copy and paste the actual error from the R Markdown output.

**Comment by sbmarsh-USGS** [comment]
Here it is.  I retyped it because it wouldn't let me copy and paste it:

Line 9
Error in parse(text = x, srcfile = src) : attempt to use zero-length variable name calls: <Anonymous> ... <Anonymous> -> parse_all.character -> parse Execution halted

**Comment by lindsaycarr** [comment]
What version of dplyr do you have? `packageVersion('dplyr')`

**Comment by lindsaycarr** [comment]
Also, check that your chunk starts with ```{ and ends with ``` and there is a line between the first chunk and then the next one that starts with ```{ . My googling has brought up chunk formatting as a possible reason for that error message

**Comment by sbmarsh-USGS** [comment]
dplyr version 0.4.3

**Comment by sbmarsh-USGS** [comment]
---
classoption: landscape
output: 
  word_document:
    reference_docx: table_style.docx
---

```{r echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
library(dataRetrieval)
library(lubridate)
library(dplyr)
library(tidyr)

source("../R/functions-ghtable.R")
source("../R/workflow-functions.R")
wy <- 2015
siteNumber <- '05404500'
output <- 'word'
``
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
wy_dates <- convertWYtoDate(wy)
wy_start <- wy_dates$wy_start
wy_end <- wy_dates$wy_end

stage_data <- readNWISdata(service = "dv", sites = siteNumber, 
                           parameterCd = "00065", startDate = "1800-01-01", 
                           endDate = wy_end)
if(nrow(stage_data)!=0){
  ghtable <- makeGageHeightTable(stage_data, wy_start)
} else {
  ghtable <- paste0("No gage height data available \n",
                  "http://waterdata.usgs.gov/nwis/inventory?agency_code=USGS&site_no=",
                  siteNumber)
}
``` 

`r isData <- !is.null(dim(ghtable))`

#`r if(!isData) {ghtable}`#

`r isWord <- output == "word"`
```{r eval=!isWord && isData, echo=FALSE, warning=FALSE, message=FALSE, results='asis'} 
library(xtable)
options(xtable.comment = FALSE)

gh_xtable <- xtable(ghtable, auto=TRUE)
print.xtable(gh_xtable, NA.string = "--", include.rownames=FALSE)
```

```{r eval=isWord && isData, echo=FALSE, warning=FALSE, message=FALSE, results='asis'} 
library(pander)
panderOptions('missing', '--')
panderOptions('digits', 4)
panderOptions('keep.trailing.zeros', TRUE)
panderOptions('table.continues', NULL)
panderOptions('table.split.table', Inf)
pander(ghtable)
```

**Comment by lindsaycarr** [comment]
@sbmarsh-USGS looks like that first chunk is the issue - there's some extra backticks (2) that are at the end. Delete those and try running.

Also, might be a good idea to update packages soon - dplyr is now at 0.5.0

**Comment by sbmarsh-USGS** [comment]
Should I update them all?  What's the best way to do that?

**Comment by lindsaycarr** [comment]
Yep, that would be a good idea. You should make sure gsplot does not get updated though.

![image](https://cloud.githubusercontent.com/assets/13220910/17986008/44be55e4-6ade-11e6-98d2-9c6113c11338.png)

Then "Select All" in the dialogue box (UNCHECK gsplot if it comes up). Then press "Install Updates" and wait for everything to finish.

**Comment by sbmarsh-USGS** [comment]
Any problem with any of the following?  I haven't tried running any tables or plots yet.

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/xml2_1.0.0.zip'
Content type 'application/zip' length 3426117 bytes (3.3 MB)
downloaded 1.6 MB

Warning in install.packages :
  downloaded length 1695744 != reported length 3426117
package ‘tibble’ successfully unpacked and MD5 sums checked
package ‘hms’ successfully unpacked and MD5 sums checked
package ‘base64enc’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  error 1 in extracting from zip file
Warning in install.packages :
  cannot open compressed file 'BH/DESCRIPTION', probable reason 'No such file or directory'
Error in install.packages : cannot open the connection

**Comment by sbmarsh-USGS** [comment]
I just tried a ghtable again and no luck.  I'll try touching base with you soon.

**Comment by lindsaycarr** [comment]
@sbmarsh-USGS I'm free to meet almost the whole day so just gchat when you're ready

**Comment by sbmarsh-USGS** [comment]
We need to add the update that if it pulls data with only one decimal place that it adds a zero at the end.  i.e.  Value of 2.6 should read 2.60.

**Comment by lindsaycarr** [comment]
@sbmarsh-USGS pull from upstream with my new changes -- this issue should be fixed!

**Comment by sbmarsh-USGS** [comment]
Looks great!
