### ISSUE TITLE
Range for x-axis on depth profiles not capturing all data

### ISSUE THREAD

**Issue by sbmarsh-USGS** [USGS-R/lakeReport#41]
I think this only happens on one plot, but for Oconomowoc Lake No. 2 (430609088262200) on 6/23/15, the specific conductance goes off the plot.  I think the top value is 584 and the minimum on the x-axis is 600.
![image](https://cloud.githubusercontent.com/assets/10731242/17909748/76d2c356-694b-11e6-9d17-1511d3497eb8.png)

**Comment by sbmarsh-USGS** [comment]
@lindsaycarr This one is still happening.  I'm guessing we'll have to adjust the code in functions-depthprofiles.R lines 90-92...yes?
****
![image](https://user-images.githubusercontent.com/10731242/41742213-fee88d28-7562-11e8-81c1-d470f777d449.png)

**Comment by lindsaycarr** [comment]
@sbmarsh-USGS this is actually a very simple fix. You have a CSV file with the ranges and Oconomowoc number 2 has 600 as the low value for specific conductance. Just change the CSV

https://github.com/USGS-R/lakeReport/blob/master/data/depthProfileRanges.csv#L14
