### ISSUE TITLE
Can we have breaks in the plot lines (stage hydrographs)?

### ISSUE THREAD

**Issue by sbmarsh-USGS** [USGS-R/lakeReport#51]
Can we have the plots show gaps in the data?  For particularly long periods of record, it would be a more accurate representation...especially when there aren't continuous data.

![image](https://cloud.githubusercontent.com/assets/10731242/19085846/79d1bd76-8a31-11e6-8845-35229f7fe431.png)

![image](https://cloud.githubusercontent.com/assets/10731242/19085882/94cebdcc-8a31-11e6-99c7-3a981b8f620b.png)

**Comment by lindsaycarr** [comment]
Need criteria for plotting data as points vs lines. Then we can add an if statement to the code.

Need criteria for what constitutes a data gap (where we would break the line). Could vary depending on length of time period of the plot. E.g. 1 yr of missing data is a gap for 20yrs, but 2 months is a gap for 5.
