### ISSUE TITLE
Potter Lake current data qwtimeseries and depth profiles.

### ISSUE THREAD

**Issue by sbmarsh-USGS** [USGS-R/lakeReport#55]
I just ran the qwtimeseries plot for the newly added Potter Lake and don't see any current (2015) data for it.  All the rest of the data look fine (except for the first few years of total phosphorus values which I think is a depth parameter code issue that I can fix in the database).

Also, I ran the depthprofiles command and got nothing.  Failed report. (Warning message: package 'dplyr' was built under R version 3.2.5)

![image](https://cloud.githubusercontent.com/assets/10731242/19780148/a238fe30-9c49-11e6-9db8-351b7903b217.png)

**Comment by lindsaycarr** [comment]
It did not pull any data past 2007-09-14, but I can see it sitting on NWIS. 
http://nwis.waterdata.usgs.gov/wi/nwis/qwdata/?site_no=424905088204000&agency_cd=USGS&inventory_output=0&rdb_inventory_output=file&TZoutput=0&pm_cd_compare=Greater%20than&radio_parm_cds=parm_cd_list&radio_multiple_parm_cds=00665%2C70953%2C32210%2C00078%2C00098&format=html_table&qw_attributes=0&qw_sample_wide=wide&rdb_qw_attributes=0&date_format=YYYY-MM-DD&rdb_compression=file&submitted_form=brief_list

**Comment by sbmarsh-USGS** [comment]
I just realized what the issue is.  Potter Lake only started back in our program this year (2016).  I assumed there were 2015 data because the cooperator asked for it, but she was mistaken about when the data started getting collected again.  Sorry!

**Comment by lindsaycarr** [comment]
Ha, good to hear! Quickest open/close on an issue ever :hand: (high five)
