### ISSUE TITLE
Add filepaths to plotNames_by_site.csv

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/lakeReport#56]
1. Stage height data needs to be csv files w/ dateTime (yyyy-mm-dd) and gageHeight columns.
2. Add file paths to plotNames_by_site.csv (within text editor, like notepad ++). Use column name `gageHeight_files`
3. Add code to grab gageHeight_files and use instead of NWIS.

**Comment by sbmarsh-USGS** [comment]
df <- read_excel("M:/Lakes/9KB25/Silver_Cumberland/Stage/silver_cumberland_stage.xlsx")

Do decimalDate workaround for Lake Winnebago.

**Comment by lindsaycarr** [comment]
Code changes (don't need csv, can use Excel w/ `readxl` package):

- Create function that takes a site number and returns the stage filepath from the `plotNames_by_site.csv`
- In `renderLakeReport`, call the new function only if it's creating a stage hydrograph. The new object should be named `filePath`.
- Change `read.csv` to `read_excel` (and add `library(readxl)`) to stagehydrograph.Rmd.
- `makeStageHydrograph_file` function does not need the `datetime_colname` and `gageheight_colname` titles
- Add to `makeStageHydrograph_file` to properly change dates to a date format, and handle the Lake Winnebago dates with:

```r
library(lubridate)
winnebago <- winnebago %>% 
  filter(!is.na(X)) %>% ## is this needed????
  mutate(decimal.date = as.numeric(decimal.date),
         dateTime = date_decimal(decimal.date)) 
```
