### ISSUE TITLE
qwtimeseries not running

### ISSUE THREAD

**Issue by sbmarsh-USGS** [USGS-R/lakeReport#62]
I tried to generate a qwtimeseries plot for 423556088365001 (Delavan Lake at Center) and got the following error message:
Quitting from lines 12-24 (qwtimeseries.Rmd)

**Comment by lindsaycarr** [comment]
I ran this and tried it with `wy <- 2016`. I did not get an error. Can you recreate and find what the error actually is? It's best to pinpoint the error by inserting `browser()` and re-sourcing the functions. The "Quitting from lines..." message doesn't tell us anything. 

```
wy <- 2015
siteNumber <- '423556088365001'
plotNames <- 'qwtimeseries'
output <- 'word'
makeReports(siteNumber, wy, plotNames, output)
```

**Comment by sbmarsh-USGS** [comment]
I followed the debugging instructions and stepped through the lines listed.  When I got to line 20, this is the error that was returned:

Error in `[.data.frame`(df, , date.time.cols) : 
  undefined columns selected

**Comment by lindsaycarr** [comment]
Great! Line 20 in `qwtimeseries.Rmd`? Or in `functions-qwtimeseries.R`?

**Comment by sbmarsh-USGS** [comment]
qwtimeseries.Rmd

**Comment by lindsaycarr** [comment]
hmm that's strange. That is not an error I would expect on that line. Can you copy and paste that line here? I just want to make sure I'm looking at the correct one.

I would try restarting R (close, then open again) and try to follow the steps again to see if you get the same error.

**Comment by sbmarsh-USGS** [comment]
Yep, got the same error. This is line 20:

endDate = wy_end)

**Comment by lindsaycarr** [comment]
You might need to select lines 17-20 and run all at once if you haven't been doing that. It is one function call, just separated to different lines for readability. Check where the parentheses start & where they end. Line 17 starts the parentheses, and Line 20 closes them for the function `readNWISqw`.

Just wondering if that's why you are seeing that error. Otherwise, I'm not sure what that is because I'm not able to recreate it.

**Comment by sbmarsh-USGS** [comment]
As I attempt to debug these, I realized I forgot what to do with the line that says "extraInfo <- list(...)" and it's not in the debugging instructions.

**Comment by sbmarsh-USGS** [comment]
I skipped the extraInfo line and re-ran the final sections and here's what I got:

Error in nchar(gageheight_filepath) : 
  object 'gageheight_filepath' not found

**Comment by lindsaycarr** [comment]
There shouldn't be gageheight_filepath for qwtimeseries, only for stagehydrograph. If you're doing stagehydrograph, check the debugging document again - I have instructions about creating the gageheight_filepath object.

**Comment by sbmarsh-USGS** [comment]
I'm honestly so stuck trying to debug this that I think I'm making it worse. I'll try and set up a meeting time in a couple of weeks when you might be available.

**Comment by lindsaycarr** [comment]
OK

**Comment by lindsaycarr** [comment]
@sbmarsh-USGS I just ran this through with no issues. Try updating all of your packages.
