### ISSUE TITLE
stage hydrograph ifelse statement about Devils Lake not working

### ISSUE THREAD

**Issue by sbmarsh-USGS** [USGS-R/lakeReport#63]
stagehydrograph.Rmd lines 27-29 include an ifelse statement for Devils Lake to only pull data starting in 1936, but when I run the stagehydrograph function for this site it still pulls data from 1922-current.
![image](https://cloud.githubusercontent.com/assets/10731242/25439665/a9136310-2a62-11e7-95f1-e987f1971643.png)

**Comment by lindsaycarr** [comment]
If you look at stagehydrograph.Rmd, the if-else only happens when we pull NWIS data. If you would like that filter to also apply to the excel files, we will need to move it.

https://github.com/USGS-R/lakeReport/blob/master/Report_templates/stagehydrograph.Rmd
