### ISSUE TITLE
y-axis labels overlap on some stage hydrographs and qwtimeseries plots

### ISSUE THREAD

**Issue by sbmarsh-USGS** [USGS-R/lakeReport#67]
If a stage hydrograph or qwtimeseries plot has y-axis values with decimal places, the y-axis title overlaps the numbers on the scale.  See the following 2 examples:
![image](https://cloud.githubusercontent.com/assets/10731242/25719501/57ff0bc8-30cf-11e7-9885-0cd162050040.png)

![image](https://cloud.githubusercontent.com/assets/10731242/25719582/82e0e6f4-30cf-11e7-9d19-dd196097e68f.png)

**Comment by lindsaycarr** [comment]
@sbmarsh-USGS trying playing around with the argument `line` in the `title` function.

Currently, `makeStageHydrograph_file` has this at the end to make the plot:
```r
stageHydrograph <- gsplot(yaxs='r') %>% 
    points(stage_data$dateTime, stage_data$gageHeight, pch=20, col="black") %>% 
    axis(side=1, at=allDates, labels=allYears) %>% 
    axis(side=3, at=allDates, labels=FALSE) %>%
    axis(side=2, n.minor=4) %>%
    title(ylab = "GAGE HEIGHT, IN FEET")
```

Check  out `?title` to learn about the argument `line`. Add it to that last line of code shown above (e.g. `title(ylab="some title", line=2)`)

**Comment by sbmarsh-USGS** [comment]
I keep playing with this.  Added line=2 and changed it up to line=10 and nothing appears to change in the plot when I run it.  I've saved it and re-sourced each time.

**Comment by sbmarsh-USGS** [comment]
Oops.  Hang on.  I was putting it in the wrong place.  I think I got it.  Will do some double-checking with other plots, etc. before I commit changes.

**Comment by sbmarsh-USGS** [comment]
I fixed the location of the title on the stage hydrographs, but haven't committed changes yet.  I was hoping to fix it on the qwtimeseries plots too, then commit so I can close this issue all at once.  But It's a little different on the qwtimeseries....do I add a line-x in the RMD file on lines 42-45? Where the title is listed?

**Comment by lindsaycarr** [comment]
Hmmm so there are two ways to add y-labels, and unfortunately I used both (sorry!). The first is to supply `ylab` as an argument to `title`. The second is to add `ylab` as an argument to your data call, e.g. `points`, which is what I did for `qwtimeseries`. So, I would actually suggest removing the `ylab` argument from the points call (used [here](https://github.com/USGS-R/lakeReport/blob/master/R/functions-qwtimeseries.R#L154)), and adding the function call `title(ylab = "")`. Then, you can use that `line` argument in `title` to get the same effect as you did in stagehydrograph. Notice the `%>%` symbol after each line - this is used to connect the functions which is special technique called piping. You'll need to add one of those.

**Comment by lindsaycarr** [comment]
Give it a go and push commits. I can comment on the PR if you don't think you quite have it

**Comment by sbmarsh-USGS** [comment]
I removed the ylab argument from points call.
Because there are 4 plots in qwtimeseries, do I need to add the function call title(ylab = "") 4 times with each title?  Also, will it go in the following location (of the functions-qwtimeseries.R):

Lines 158-162:
    axis(side = 2, reverse = axisFlip, n.minor = y_n.minor) %>% 
    axis(side = 4, reverse = axisFlip, n.minor = y_n.minor, labels = FALSE) %>%  
    axis(side = 1, at = x_at, n.minor = x_n.minor, labels = year(x_at)) %>% 
    axis(side = 3, at = x_at, n.minor = x_n.minor, labels = FALSE) %>%
    title(ylab = "TOTAL PHOSPHORUS CONCENTRATION IN MILLIGRAMS PER LITER", line=2)

**Comment by lindsaycarr** [comment]
You should only need to have the one `title(ylab=` call. It is nested inside two functions (makeTimeseriesPlot --> plotSetup). `makeTimeseriesPlot` is used with different inputs to make each of the 4 plots (see the last 4 lines in `qwtimeseries.Rmd`).

**Comment by sbmarsh-USGS** [comment]
I've tried several iterations of this, with none of them successful.  Is it even in the right location above?

**Comment by lindsaycarr** [comment]
Yes, looks like it is

**Comment by sbmarsh-USGS** [comment]
parm_plot <- gsplot() %>% 
    # setting up plot limits
    points(NA, NA, 
           xlim = c(date_info$firstDate, date_info$lastDate),
           ylim = c(ymin, ymax)) %>% 
    
    # formatting axes
    axis(side = 2, reverse = axisFlip, n.minor = y_n.minor) %>% 
    axis(side = 4, reverse = axisFlip, n.minor = y_n.minor, labels = FALSE) %>%  
    axis(side = 1, at = x_at, n.minor = x_n.minor, labels = year(x_at)) %>% 
    axis(side = 3, at = x_at, n.minor = x_n.minor, labels = FALSE) %>%
    title(ylab = title, line=2)
