### ISSUE TITLE
Add titles to depth profile and qwtimeseries pages

### ISSUE THREAD

**Issue by sbmarsh-USGS** [USGS-R/lakeReport#74]
For depth profiles, an example header would read:
Line 1 in bold, centered: 424929088231300 LAKE BEULAH STATION 2 NEAR EAST TROY, WI
Line 2, centered, smaller font than Line 1: LAKE-DEPTH PROFILES, MAY 7 TO AUGUST 27, 2015

For qwtimeseries, add header in bold at top of page: 424929088231300 LAKE BEULAH STATION 2 NEAR EAST TROY, WI
Add title below plots: Surface total phosphorus, chlorophyll _a_ concentrations, Secchi depths, and TSI data.

As long as we are doing this, we can add a header and title to the stagehydrographs as well.

- [x] qwtimeseries

- [ ] depthprofiles

**Comment by sbmarsh-USGS** [comment]
No even sure where to begin adding title to the depthprofiles plots, given the complexity of the plots.  I will check with Dale though on perhaps adding color to the lines and legends rather than moving them outside the plots.

**Comment by sbmarsh-USGS** [comment]
I adjusted positioning of many of the subtitles and the margins.  I committed and pushed those changes, but no matter what I do with the oma parameters, I cannot get the main title to appear.  I am at a loss.

**Comment by sbmarsh-USGS** [comment]
Depth profiles is working for a plot containing 4 or 5 dates, but not for 2.  The two plots aren't centered and the main title and sub titles are in the wrong location.

**Comment by lindsaycarr** [comment]
@sbmarsh-USGS could you put up a quick screenshot of how it looks?

**Comment by sbmarsh-USGS** [comment]
@lindsaycarr 

![image](https://user-images.githubusercontent.com/10731242/40367475-22e91b10-5d9f-11e8-9a7d-411d299af4ec.png)

**Comment by lindsaycarr** [comment]
So, we just need to change the `plot.new` calls in the "extra plots" code of `depthprofiles.Rmd` so that they are correctly adding blank plots. I'm using blank plots as placeholders, so we can center them under the titles.

Add `blank.plot <- gsplot(bty="n")` to create a blank plot with no border right below where we create `gs.dummy`. Then, change each `plot.new()` call (see here and here) to `print(blank.plot)`.

**Comment by sbmarsh-USGS** [comment]
@lindsaycarr If you look at Pull Requests, I changed that gs.dummy to gs top and bottom plots to match the 2x5 plot section so that the Title and subtitle would appear correctly.  Do I need to revert back?  Or should I add the blank.plot under gs. setup.top?

Also, I can't "see here and here" from above...there are no links...

**Comment by lindsaycarr** [comment]
Ignore the `here and here` (I just deleted it). I was going to link to specific lines, but couldn't do that with the .Rmd file type.

Just add it under the `gs.setup.top`

**Comment by sbmarsh-USGS** [comment]
Awesome!  Now am wondering if there is a way to auto-adjust the DEPTH, IN METERS y-axis title.  I was playing with the line value to no avail. Would this have to do with outer=TRUE or not?

![image](https://user-images.githubusercontent.com/10731242/41250056-75a37b70-6d7b-11e8-88ab-8ed9a2aecc3b.png)

**Comment by sbmarsh-USGS** [comment]
Yes!
![image](https://user-images.githubusercontent.com/10731242/41251211-d9d8ce12-6d7e-11e8-8062-963361b1d04f.png)
